services:
  - type: web
    name: demo-office-management
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE
        sync: false
      - key: ADMIN_EMAIL
        sync: false
